package cuotas.model.domain.factura;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;






import common.model.domain.datos.Estado;
import common.model.domain.datos.GenericBean;
import cuotas.model.domain.datos.Grupo;
import cuotas.model.domain.datos.Partida;

/**
 * CbrTipos generated by hbm2java
 */
public class FacturaItemTipo  extends GenericBean<Integer> implements java.io.Serializable {
	private static final long serialVersionUID = -8664101245039518290L;

	//private Integer id;
	
	private RubroCobro rubroCobro;
	private String descripcion;
	private Integer codigo;
	private Double precio;
	private Set<FacturaItem> facturaItem = new HashSet<FacturaItem>(0);
	private Estado estado;
	private Partida partida;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);
	private Set<Grupo> grupos_mora = new HashSet<Grupo>(0);
	
	public FacturaItemTipo() {
	}

	public FacturaItemTipo(RubroCobro rubroCobro) {
		this.rubroCobro = rubroCobro;
	}

	public FacturaItemTipo(RubroCobro rubroCobro, String descripcion, Double precio,
			Set<FacturaItem> facturaItems) {
		this.rubroCobro = rubroCobro;
		this.descripcion = descripcion;
		this.precio = precio;
		this.facturaItem = facturaItems;
	}
/*
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	

	public boolean equals(FacturaItemTipo FacturaItemTipo){
		boolean respuesta;
		if(super.equals(FacturaItemTipo)){
			System.out.println(this.getId()+"="+FacturaItemTipo.getId()); 
			respuesta = true;
		}else{
			System.out.println(this.getId()+"="+FacturaItemTipo.getId());
			respuesta = false; 
		}
		return respuesta; 
	}
	public int hashCode() {
		
	}
	
	*/
	public RubroCobro getRubroCobro() {
		return this.rubroCobro;
	}

	public Set<Grupo> getGrupos_mora() {
		return grupos_mora;
	}

	public void setGrupos_mora(Set<Grupo> grupos_mora) {
		this.grupos_mora = grupos_mora;
	}

	public Partida getPartida() {
		return partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	public Integer getCodigo() {
		return codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public void setRubroCobro(RubroCobro rubroCobro) {
		this.rubroCobro = rubroCobro;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		if(descripcion.equals("")){
			//FIXME - mensaje de error
		}else{
			this.descripcion = descripcion;	
		}
	}
	public Double getPrecio() {
		return this.precio;
	}
	public void setPrecio(Double precio) {
		this.precio = precio;
	}
	public Set<FacturaItem> getCbrItems() {
		return this.facturaItem;
	}
	public void setCbrItems(Set<FacturaItem> facturaItems) {
		this.facturaItem = facturaItems;
	}

	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}

	public Set<FacturaItem> getFacturaItem() {
		return facturaItem;
	}

	public void setFacturaItem(Set<FacturaItem> facturaItem) {
		this.facturaItem = facturaItem;
	}

	public Set<Grupo> getGrupos() {
		return grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}
}
