package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GAuditoId generated by hbm2java
 */
public class GAuditoId implements java.io.Serializable {

	private Date fecha;
	private String operador;
	private String descri;

	public GAuditoId() {
	}

	public GAuditoId(Date fecha) {
		this.fecha = fecha;
	}

	public GAuditoId(Date fecha, String operador, String descri) {
		this.fecha = fecha;
		this.operador = operador;
		this.descri = descri;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GAuditoId))
			return false;
		GAuditoId castOther = (GAuditoId) other;

		return ((this.getFecha() == castOther.getFecha()) || (this.getFecha() != null
				&& castOther.getFecha() != null && this.getFecha().equals(
				castOther.getFecha())))
				&& ((this.getOperador() == castOther.getOperador()) || (this
						.getOperador() != null
						&& castOther.getOperador() != null && this
						.getOperador().equals(castOther.getOperador())))
				&& ((this.getDescri() == castOther.getDescri()) || (this
						.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri()
						.equals(castOther.getDescri())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		result = 37 * result
				+ (getOperador() == null ? 0 : this.getOperador().hashCode());
		result = 37 * result
				+ (getDescri() == null ? 0 : this.getDescri().hashCode());
		return result;
	}

}
