package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GAudito generated by hbm2java
 */
public class GAudito implements java.io.Serializable {

	private GAuditoId id;

	public GAudito() {
	}

	public GAudito(GAuditoId id) {
		this.id = id;
	}

	public GAuditoId getId() {
		return this.id;
	}

	public void setId(GAuditoId id) {
		this.id = id;
	}

}
