package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOpcion generated by hbm2java
 */
public class GOpcion implements java.io.Serializable {

	private GOpcionId id;

	public GOpcion() {
	}

	public GOpcion(GOpcionId id) {
		this.id = id;
	}

	public GOpcionId getId() {
		return this.id;
	}

	public void setId(GOpcionId id) {
		this.id = id;
	}

}
