package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * GOpcionId generated by hbm2java
 */
public class GOpcionId implements java.io.Serializable {

	private String codigo;
	private String descri;
	private Integer activo;
	private String operador;
	private Date fecha;

	public GOpcionId() {
	}

	public GOpcionId(String codigo) {
		this.codigo = codigo;
	}

	public GOpcionId(String codigo, String descri, Integer activo,
			String operador, Date fecha) {
		this.codigo = codigo;
		this.descri = descri;
		this.activo = activo;
		this.operador = operador;
		this.fecha = fecha;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Integer getActivo() {
		return this.activo;
	}

	public void setActivo(Integer activo) {
		this.activo = activo;
	}

	public String getOperador() {
		return this.operador;
	}

	public void setOperador(String operador) {
		this.operador = operador;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GOpcionId))
			return false;
		GOpcionId castOther = (GOpcionId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this
				.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(
				castOther.getCodigo())))
				&& ((this.getDescri() == castOther.getDescri()) || (this
						.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri()
						.equals(castOther.getDescri())))
				&& ((this.getActivo() == castOther.getActivo()) || (this
						.getActivo() != null
						&& castOther.getActivo() != null && this.getActivo()
						.equals(castOther.getActivo())))
				&& ((this.getOperador() == castOther.getOperador()) || (this
						.getOperador() != null
						&& castOther.getOperador() != null && this
						.getOperador().equals(castOther.getOperador())))
				&& ((this.getFecha() == castOther.getFecha()) || (this
						.getFecha() != null
						&& castOther.getFecha() != null && this.getFecha()
						.equals(castOther.getFecha())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result
				+ (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result
				+ (getActivo() == null ? 0 : this.getActivo().hashCode());
		result = 37 * result
				+ (getOperador() == null ? 0 : this.getOperador().hashCode());
		result = 37 * result
				+ (getFecha() == null ? 0 : this.getFecha().hashCode());
		return result;
	}

}
