package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOperopc generated by hbm2java
 */
public class GOperopc implements java.io.Serializable {

	private GOperopcId id;

	public GOperopc() {
	}

	public GOperopc(GOperopcId id) {
		this.id = id;
	}

	public GOperopcId getId() {
		return this.id;
	}

	public void setId(GOperopcId id) {
		this.id = id;
	}

}
