package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOperador generated by hbm2java
 */
public class GOperador implements java.io.Serializable {

	private GOperadorId id;

	public GOperador() {
	}

	public GOperador(GOperadorId id) {
		this.id = id;
	}

	public GOperadorId getId() {
		return this.id;
	}

	public void setId(GOperadorId id) {
		this.id = id;
	}

}
