package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOpecateId generated by hbm2java
 */
public class GOpecateId implements java.io.Serializable {

	private String codigo;
	private String descri;

	public GOpecateId() {
	}

	public GOpecateId(String codigo) {
		this.codigo = codigo;
	}

	public GOpecateId(String codigo, String descri) {
		this.codigo = codigo;
		this.descri = descri;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GOpecateId))
			return false;
		GOpecateId castOther = (GOpecateId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this
				.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(
				castOther.getCodigo())))
				&& ((this.getDescri() == castOther.getDescri()) || (this
						.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri()
						.equals(castOther.getDescri())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result
				+ (getDescri() == null ? 0 : this.getDescri().hashCode());
		return result;
	}

}
