package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOperopcId generated by hbm2java
 */
public class GOperopcId implements java.io.Serializable {

	private String categoria;
	private String opcion;

	public GOperopcId() {
	}

	public GOperopcId(String categoria, String opcion) {
		this.categoria = categoria;
		this.opcion = opcion;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getOpcion() {
		return this.opcion;
	}

	public void setOpcion(String opcion) {
		this.opcion = opcion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GOperopcId))
			return false;
		GOperopcId castOther = (GOperopcId) other;

		return ((this.getCategoria() == castOther.getCategoria()) || (this
				.getCategoria() != null
				&& castOther.getCategoria() != null && this.getCategoria()
				.equals(castOther.getCategoria())))
				&& ((this.getOpcion() == castOther.getOpcion()) || (this
						.getOpcion() != null
						&& castOther.getOpcion() != null && this.getOpcion()
						.equals(castOther.getOpcion())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCategoria() == null ? 0 : this.getCategoria().hashCode());
		result = 37 * result
				+ (getOpcion() == null ? 0 : this.getOpcion().hashCode());
		return result;
	}

}
