package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOpecate generated by hbm2java
 */
public class GOpecate implements java.io.Serializable {

	private GOpecateId id;

	public GOpecate() {
	}

	public GOpecate(GOpecateId id) {
		this.id = id;
	}

	public GOpecateId getId() {
		return this.id;
	}

	public void setId(GOpecateId id) {
		this.id = id;
	}

}
