package cuotas.model.domain.grupo;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

/**
 * GOperadorId generated by hbm2java
 */
public class GOperadorId implements java.io.Serializable {

	private String codigo;
	private String descri;
	private String desprt;
	private String mail;
	private String secreto;
	private String categoria;
	private String obser;

	public GOperadorId() {
	}

	public GOperadorId(String codigo, String categoria) {
		this.codigo = codigo;
		this.categoria = categoria;
	}

	public GOperadorId(String codigo, String descri, String desprt,
			String mail, String secreto, String categoria, String obser) {
		this.codigo = codigo;
		this.descri = descri;
		this.desprt = desprt;
		this.mail = mail;
		this.secreto = secreto;
		this.categoria = categoria;
		this.obser = obser;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public String getDesprt() {
		return this.desprt;
	}

	public void setDesprt(String desprt) {
		this.desprt = desprt;
	}

	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public String getSecreto() {
		return this.secreto;
	}

	public void setSecreto(String secreto) {
		this.secreto = secreto;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getObser() {
		return this.obser;
	}

	public void setObser(String obser) {
		this.obser = obser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GOperadorId))
			return false;
		GOperadorId castOther = (GOperadorId) other;

		return ((this.getCodigo() == castOther.getCodigo()) || (this
				.getCodigo() != null
				&& castOther.getCodigo() != null && this.getCodigo().equals(
				castOther.getCodigo())))
				&& ((this.getDescri() == castOther.getDescri()) || (this
						.getDescri() != null
						&& castOther.getDescri() != null && this.getDescri()
						.equals(castOther.getDescri())))
				&& ((this.getDesprt() == castOther.getDesprt()) || (this
						.getDesprt() != null
						&& castOther.getDesprt() != null && this.getDesprt()
						.equals(castOther.getDesprt())))
				&& ((this.getMail() == castOther.getMail()) || (this.getMail() != null
						&& castOther.getMail() != null && this.getMail()
						.equals(castOther.getMail())))
				&& ((this.getSecreto() == castOther.getSecreto()) || (this
						.getSecreto() != null
						&& castOther.getSecreto() != null && this.getSecreto()
						.equals(castOther.getSecreto())))
				&& ((this.getCategoria() == castOther.getCategoria()) || (this
						.getCategoria() != null
						&& castOther.getCategoria() != null && this
						.getCategoria().equals(castOther.getCategoria())))
				&& ((this.getObser() == castOther.getObser()) || (this
						.getObser() != null
						&& castOther.getObser() != null && this.getObser()
						.equals(castOther.getObser())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCodigo() == null ? 0 : this.getCodigo().hashCode());
		result = 37 * result
				+ (getDescri() == null ? 0 : this.getDescri().hashCode());
		result = 37 * result
				+ (getDesprt() == null ? 0 : this.getDesprt().hashCode());
		result = 37 * result
				+ (getMail() == null ? 0 : this.getMail().hashCode());
		result = 37 * result
				+ (getSecreto() == null ? 0 : this.getSecreto().hashCode());
		result = 37 * result
				+ (getCategoria() == null ? 0 : this.getCategoria().hashCode());
		result = 37 * result
				+ (getObser() == null ? 0 : this.getObser().hashCode());
		return result;
	}

}
