package cuotas.model.domain.datos;
// default package
// Generated 11/06/2012 12:24:34 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;





import common.model.domain.datos.Estado;
import common.model.domain.datos.GenericBean;
import common.model.domain.datosPersonales.TipoDocumento;
import common.model.domain.error.ErrorParametro;
import cuotas.model.domain.factura.FacturaItemTipo;


/**
 * Grupo generated by hbm2java
 */
public class Grupo extends GenericBean<Long>  implements java.io.Serializable {
	private static final long serialVersionUID = -7576830087433901844L;
	
	private String descripcion;
	private Integer anioCuota;
	private Integer tipoInforme;
	private String concepto1;
	private String concepto2;	
	private String nombreTitulo;
	private Character ctrlPago;
	private Integer vtoDias;
	private Integer vtoPlus;
	
	private Double vtoMonto;
	
	private Double conceptoUnoMonto;
	private Double conceptoDosMonto; 
	
	private Integer comision;
	private Long codigo;
	private Long numero; //identificador del grupo para pago facil
	private Character cobraMora;
	private Set<Pago> pagos = new HashSet<Pago>(0);
	private Set<Cuota> cuotas = new HashSet/*TreeSet*/<Cuota>(0);	
	private Estado estado;
	private Carrera carrera;
	private Integer cantidadCuotas;
	private Partida partida;
	private FacturaItemTipo facturaItemTipo;
	private FacturaItemTipo facturaItemTipoMora;
	private Set<UsuarioCuotas> usuariosGrupo = new HashSet<UsuarioCuotas>(0);
	/*
	private Character tramiteGrado;
	private Character tramitePosgrado;
	private Character tramiteIngreso;
	
	public Character getTramiteGrado() {
		return tramiteGrado;
	}

*/
	public Grupo() {
		super();
		this.estado = new Estado(Estado.ACTIVO);
	}

	public Grupo(String descri, Integer anoInicio, Integer tipoInforme,
			String concepto1, String concepto2, Carrera carrera, String nombreTitulo, Character ctrlPago,
			Integer vtoDias, Integer vtoPlus, Integer comision,
			Set<Pago> pagos, Set<Cuota> cuotas) {
		this.descripcion = descri;
		this.anioCuota = anoInicio;
		this.tipoInforme = tipoInforme;
		this.concepto1 = concepto1;
		this.concepto2 = concepto2;
		this.carrera = carrera;
		this.nombreTitulo = nombreTitulo;
		this.ctrlPago = ctrlPago;
		this.vtoDias = vtoDias;
		this.vtoPlus = vtoPlus;
		this.comision = comision;
		this.pagos = pagos;
		this.cuotas = cuotas;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descri) {
		if(!this.deboEjecutarValidaciones() || descri.length() < 255){
			this.descripcion = limpiarString(descri);
		}else{
			throw new ErrorParametro("La descripcion del grupo es invalida. \\n La descripcion execedio los 255 caracteres");
		}
	}
	
	public FacturaItemTipo getFacturaItemTipoMora() {
		return facturaItemTipoMora;
	}

	public void setFacturaItemTipoMora(FacturaItemTipo facturaItemTipoMora) {
		this.facturaItemTipoMora = facturaItemTipoMora;
	}

	private String limpiarString(String s){
		s = s.replace("\"" , "&#34;");
		return s;
	}
	
	public Integer getCantidadCuotas() {
		return cantidadCuotas;
	}

	public void setCantidadCuotas(Integer cantidadCuotas) {
		this.cantidadCuotas = cantidadCuotas;
	}

	public Integer getAnioCuota() {
		return this.anioCuota;
	}

	public void setAnioCuota(Integer anioCuota) {
		this.anioCuota = anioCuota;
	}

	public Integer getTipoInforme() {
		return this.tipoInforme;
	}

	public void setTipoInforme(Integer tipoInforme) {
		this.tipoInforme = tipoInforme;
	}

	public String getConcepto1() {
		return this.concepto1;
	}

	public void setConcepto1(String concepto1) {
		if(!this.deboEjecutarValidaciones() || concepto1.length() < 255){
			this.concepto1 = concepto1;
		}else{
			throw new ErrorParametro("El Concepto1 del grupo es invalido. \\n El concepto1 execedio los 255 caracteres");
		}
		
	}

	public String getConcepto2() {
		return this.concepto2;
	}

	public void setConcepto2(String concepto2) {
		if(!this.deboEjecutarValidaciones() || concepto2.length() < 255){
			this.concepto2 = concepto2;
		}else{
			throw new ErrorParametro("El Concepto2 del grupo es invalido. \\n El concepto2 execedio los 255 caracteres");
		}
	}

	

	public Carrera getCarrera() {
		return carrera;
	}

	public void setCarrera(Carrera carrera) {
		this.carrera = carrera;
	}

	public String getNombreTitulo() {
		return this.nombreTitulo;
	}

	public void setNombreTitulo(String nombreTitulo) {
		if(!this.deboEjecutarValidaciones()){
			this.nombreTitulo = nombreTitulo;	
		}else{
			throw new ErrorParametro("Nombre del Titulo invalido. \\n El titulo execedio los 255 caracteres");
		}
	}

	public Character getCtrlPago() {
		return this.ctrlPago;
	}

	public void setCtrlPago(Character ctrlPago) {
		this.ctrlPago = ctrlPago;
	}

	public Integer getVtoDias() {
		return this.vtoDias;
	}

	public void setVtoDias(Integer vtoDias) {
		this.vtoDias = vtoDias;
	}

	public Integer getVtoPlus() {
		return this.vtoPlus;
	}

	public void setVtoPlus(Integer vtoPlus) {
		this.vtoPlus = vtoPlus;
	}

	public Integer getComision() {
		return this.comision;
	}

	public void setComision(Integer comision) {
		this.comision = comision;
	}

	
	public Set<Pago> getPagos() {
		return pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

	public Set<Cuota> getCuotas() {
		return cuotas;
	}
	public void setCuotas(Set<Cuota> cuotas) {
		this.cuotas = cuotas;
	}

	/**
	 * Agrega una cuota al grupo, si existe una igual (usando equals!) la actualiza.
	 * @param cuota
	 */
	public void addCuota(Cuota cuota){
		if(this.cuotas.contains(cuota))
			this.cuotas.remove(cuota);
		this.cuotas.add(cuota);
	}
	public void removeCuota(Cuota cuota){
		this.cuotas.remove(cuota);
	}
	public void addPago(Pago pago){
		this.pagos.add(pago);
	}
	public void removePago(Pago pago){
		this.pagos.remove(pago);
	}
	
	public Estado getEstado() {
		return estado;
	}

	public void setEstado(Estado estado) {
		this.estado = estado;
	}
	
	public int compareTo(Object o){
        Grupo g = (Grupo)o;       
        return this.getId().compareTo(g.getId());
    }

	public Double getVtoMonto() {
		return vtoMonto;
	}

	public void setVtoMonto(Double vtoMonto) {
		this.vtoMonto = vtoMonto;
	}

	public Long getCodigo() {
		return codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}

	public Double getConceptoUnoMonto() {
		return conceptoUnoMonto;
	}

	public void setConceptoUnoMonto(Double conceptoUnoMonto) {
		this.conceptoUnoMonto = conceptoUnoMonto;
	}

	public Double getConceptoDosMonto() {
		return conceptoDosMonto;
	}

	public void setConceptoDosMonto(Double conceptoDosMonto) {
		this.conceptoDosMonto = conceptoDosMonto;
	}

	public Character getCobraMora() {
		return cobraMora;
	}

	public void setCobraMora(Character cobraMora) {
		this.cobraMora = cobraMora;
	}

	public Partida getPartida() {
		return partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}


	public FacturaItemTipo getFacturaItemTipo() {
		return facturaItemTipo;
	}

	public void setFacturaItemTipo(FacturaItemTipo facturaItemTipo) {
		this.facturaItemTipo = facturaItemTipo;
	}

	public Long getNumero() {
		return numero;
	}

	public void setNumero(Long numero) {
		this.numero = numero;
	}

	public Set<UsuarioCuotas> getusuariosGrupo() {
		return usuariosGrupo;
	}

	public void setUsuariosGrupo(Set<UsuarioCuotas> usuarios) {
		this.usuariosGrupo = usuarios;
	}

	public void addUsuarioGrupo(UsuarioCuotas usuario){
		this.usuariosGrupo.add(usuario);
	}
	public void removeUsuarioGrupo(UsuarioCuotas usuario){
		this.usuariosGrupo.remove(usuario);
	}	
	
	
	public boolean equals(Object o){
		boolean res = false;
		try{
			Grupo g = (Grupo)o;
		if(g.getId().equals(this.getId()))	
				res = true;
		}catch(Exception e){
			res = false;
		}
		return res;
	}
	
	public String toString() {
		return  this.codigo+ "-"+this.descripcion ;
	} 
	
/*
	public void setTramiteGrado(Character tramiteGrado) {
		this.tramiteGrado = tramiteGrado;
	}

	public Character getTramitePosgrado() {
		return tramitePosgrado;
	}

	public void setTramitePosgrado(Character tramitePosgrado) {
		this.tramitePosgrado = tramitePosgrado;
	}

	public Character getTramiteIngreso() {
		return tramiteIngreso;
	}

	public void setTramiteIngreso(Character tramiteIngreso) {
		this.tramiteIngreso = tramiteIngreso;
	}
	*/
}
